config/routes.rb
Rails.application.routes.draw do
  
  
  devise_for :customers, controllers: {
  sessions:      'customers/sessions',
  passwords:     'customers/passwords',
  registrations: 'customers/registrations'
}

  devise_for :admin, controllers: {
  sessions:      'admins/sessions',
  passwords:     'admins/passwords',
  registrations: 'admins/registrations'
}

  namespace :admin do
    resources :customers, only: [:index, :show, :edit, :update]
    resources :order_details, only: [:update]
    resources :orders, only: [:show, :update]
    resources :genres
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    get '/' => 'homes#top' 
  end
  
  scope module: :public do
    root to: 'homes#top'
    get '/about' => 'homes#about'
    resources :items, only: [:index, :show]
    resources :cart_items, only: [:index, :update, :destroy, :create] do
      collection do
        delete :destroy_all
      end
    end
    resources :customers, only: [:show, :edit, :update] do
      collection do
        get :confilm
      end
    end
    patch '/withdrawal' => 'customers#withdrawal'
    resources :orders, only: [:new, :create, :index, :show] do
      collection do
        post :confilm
        get :complete
      end
    end
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  
  def full_name
    last_name + first_name
  end
  
  def full_name_kana
    last_name_kana + first_name_kana
  end
  
  def active_for_authentication?
    super && (self.is_active === "vaild")
  end
  
  enum is_active: { vaild: true, invaild: false }
  
  
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  def index
    @customers = Customer.page(params[:page]).order(:id)
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    @customer.update(customer_params)
    redirect_to admin_customer_path(@customer)
  end
  
  private
  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :email, :postal_code, :address, :telephone_number, :is_delete)
  end
end

app/controllers/customers/confirmations_controller.rb
# frozen_string_literal: true

class Customers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customers/passwords_controller.rb
# frozen_string_literal: true

class Customers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customers/registrations_controller.rb
# frozen_string_literal: true

class Customers::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    root_path(resource)
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customers/sessions_controller.rb
# frozen_string_literal: true

class Customers::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/customers/unlocks_controller.rb
# frozen_string_literal: true

class Customers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<main>
  <h1><%= @customer.full_name %>さんの会員情報編集</h1>
  <%= form_with model: @customer, url:admin_customer_path(@customer), local:true do |f| %>
  <div class="form-field">
    <div class="form_group">
      <p>会員ID</p>
      <p><%= @customer.id %></p>
    </div>
    <div class="form_group">
      <p>氏名</p>
      <div class="form_group_inner">
        <%= f.label :last_name, class: 'hidden-label' %>
        <%= f.text_field :last_name, autofocus: true, autocomplete: "last_name", class: 'name-box left' %>
      </div>
      <div class="form_group_inner">
        <%= f.label :first_name, class: 'hidden-label' %>
        <%= f.text_field :first_name, autofocus: true, autocomplete: "first_name", class: 'name-box' %>
      </div>
    </div>
    <div class="form_group">
      <p>フリガナ</p>
      <div class="form_group_inner">
        <%= f.label :last_name_kana, class: 'hidden-label' %>
        <%= f.text_field :last_name_kana, autofocus: true, autocomplete: "last_name_kana", class: 'name-box left' %>
      </div>
      <div class="form_group_inner">
        <%= f.label :first_name_kana, class: 'hidden-label' %>
        <%= f.text_field :first_name_kana, autofocus: true, autocomplete: "first_name_kana", class: 'name-box' %>
      </div>
    </div>
    <div class="form_group">
      <p><%= f.label :postal_code, "郵便番号" %></p>
      <div class="form_group_inner">
        <%= f.text_field :postal_code, autofocus: true, autocomplete: "postal_code", class: 'form-box' %>
      </div>
    </div>
    <div class="form_group">
      <p><%= f.label :address, "住所" %></p>
      <div class="form_group_inner">
        <%= f.text_field :address, autofocus: true, autocomplete: "address", class: 'address-box' %>
      </div>
    </div>
    <div class="form_group">
      <p><%= f.label :telephone_number, "電話番号" %></p>
      <div class="form_group_inner">
        <%= f.text_field :telephone_number, autofocus: true, autocomplete: "telephone_number", class: 'form-box' %>
      </div>
    </div>
    <div class="form_group">
      <p><%= f.label :email, "メールアドレス" %></p>
      <div class="form_group_inner">
        <%= f.email_field :email, autofocus: true, autocomplete: "email", class: 'form-box' %>
      </div>
    </div>
    <div class="form_group">
      <p><%= f.label :is_active, "会員ステータス" %></p>
      <div class="form_group_inner">
        <%= f.radio_button :is_active, Customer.is_actives.key(true) %>
        <%= f.label :is_active, Customer.is_actives_i18n[:vaild] %>
        <%= f.radio_button :is_active, Customer.is_actives.key(false) %>
        <%= f.label :is_active, Customer.is_actives_i18n[:invaild] %>
      </div>
    </div>
    <div class="submit-button">
      <%= f.submit "保存する", class: 'button' %>
    </div>
  </div>
  <% end %>
</main>

app/views/admin/customers/index.html.erb
<main>
  <h1>会員一覧</h1>
  <div class="customer-list">
    <div class="customer-list_name">
      <ul>
        <li>会員ID</li>
        <li>氏名</li>
        <li>メールアドレス</li>
        <li>ステータス</li>
      </ul>
    </div>
    <div class="customer-list_content">
    <% @customers.each do |customer| %>
      <ul>
        <li><%= customer.id %></li>
        <li><%= link_to customer.full_name, admin_customer_path(customer), class: 'link' %></li>
        <li><%= customer.email %></li>
        <li><%= customer.is_active_i18n %></li>
      </ul>
    <% end %>
    </div>
  </div>
  <%= paginate @customers %>
</main>

app/views/admin/customers/show.html.erb
<main>
  <h1><%= @customer.full_name %>さんの会員詳細</h1>
  <div class="customer-content">
    <ul>
      <li>
        <dl>
          <dt>会員ID</dt>
          <dd><%= @customer.id %></dd>
        </dl>
      </li>
      <li>
        <dl>
          <dt>氏名</dt>
          <dd><%= @customer.full_name %></dd>
        </dl>
      </li>
      <li>
        <dl>
          <dt>フリガナ</dt>
          <dd><%= @customer.full_name_kana %></dd>
        </dl>
      </li>
      <li>
        <dl>
          <dt>郵便番号</dt>
          <dd><%= @customer.postal_code %></dd>
        </dl>
      </li>
      <li>
        <dl>
          <dt>住所</dt>
          <dd><%= @customer.address %></dd>
        </dl>
      </li>
      <li>
        <dl>
          <dt>電話番号</dt>
          <dd><%= @customer.telephone_number %></dd>
        </dl>
      </li>
      <li>
        <dl>
          <dt>メールアドレス</dt>
          <dd><%= @customer.email %></dd>
        </dl>
      </li>
      <li>
        <dl>
          <dt>会員ステータス</dt>
          <dd><%= @customer.is_active_i18n %></dd>
        </dl>
      </li>
    </ul>
    <div class="customer-content_action">
      <p><%= link_to "編集する", edit_admin_customer_path(@customer), class: 'button' %></p>
      <p><%= link_to "注文履歴一覧を見る", admin_path, class: 'button' %></p>
    </div>
  </div>
</main>

app/views/admin/customers/update.html.erb
<h1>Admin::Customers#update</h1>
<p>Find me in app/views/admin/customers/update.html.erb</p>