config/routes.rb
Rails.application.routes.draw do
  
  
  devise_for :customers, controllers: {
  sessions:      'customers/sessions',
  passwords:     'customers/passwords',
  registrations: 'customers/registrations'
}

  devise_for :admin, controllers: {
  sessions:      'admins/sessions',
  passwords:     'admins/passwords',
  registrations: 'admins/registrations'
}

  namespace :admin do
    resources :customers, only: [:index, :show, :edit, :update]
    resources :order_details, only: [:update]
    resources :orders, only: [:show, :update]
    resources :genres
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    get '/' => 'homes#top' 
  end
  
  scope module: :public do
    root to: 'homes#top'
    get '/about' => 'homes#about'
    resources :items, only: [:index, :show]
    resources :cart_items, only: [:index, :update, :destroy, :create] do
      collection do
        delete :destroy_all
      end
    end
    resources :customers, only: [:show, :edit, :update] do
      collection do
        get :confilm
      end
    end
    patch '/withdrawal' => 'customers#withdrawal'
    resources :orders, only: [:new, :create, :index, :show] do
      collection do
        post :confilm
        get :complete
      end
    end
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
    
  belongs_to :customer
  
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :name, presence: true
  
  def full_address
    '〒' + postal_code + ' ' + address + ' ' + name
  end
end

app/models/addresse.rb
class Addresse < ApplicationRecord
  
  belongs_to :customer
  
  def full_address
    '〒' + postal_code + ' ' + address + ' ' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  
  belongs_to :customer
  belongs_to :item
  
  def subtotal
    item.tax_price * amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  
  def full_name
    last_name + first_name
  end
  
  def full_name_kana
    last_name_kana + first_name_kana
  end
  
  def active_for_authentication?
    super && (self.is_active === "vaild")
  end
  
  enum is_active: { vaild: true, invaild: false }
  
  
end

app/models/genre.rb
class Genre < ApplicationRecord
  
  has_many :items
  
  validates :name, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
  
  has_many :cart_items, dependent: :destroy
  belongs_to :genre
  attachment :image
  
  def tax_price
    (self.price * 1.10).round
  end
  
  enum is_active: { onsale: true, offsale: false }
  
  validates :image, presence: true
  validates :name, presence: true
  validates :introduction, presence: true
  validates :genre_id, presence: true
  validates :price, presence: true
  validates :is_active, inclusion: { in: Item.is_actives.keys }
  
end

app/models/order.rb
class Order < ApplicationRecord
  
  belongs_to :customer
  has_many :order_details, dependent: :destroy
  
  def subtotal
    order_detail.price * order_detail.amount
  end
  
  def middle_address
    address + ' ' + name
  end
  
  enum payment: { credit_card: 0, transfer: 1 }
  enum status: { a: 0, b: 1, c: 2, d: 3, e: 4  }
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  
  belongs_to :order
  belongs_to :item
  
  def subtotal
    price * amount
  end
  
  enum making_status: { not_status: 0, middle: 1, complete: 2 }
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
    @genres = Genre.all
    @genre = Genre.new
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to admin_genres_path
    else
      @genres = Genre.all
      render :index
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to admin_genres_path
  end
  
  private
  
  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.page(params[:page]).order(:id)
    @order_detail = OrderDetail.find_by(params[:id])
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  
  def new
    @item = Item.new
  end

  def index
    @items = Item.page(params[:page]).per(10).order(:id)
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item)
    else
      render :new
    end
    
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_item_path(@item)
  end
  
  private
  
  def item_params
    params.require(:item).permit(:name, :image, :introduction, :genre_id, :price, :is_active)
  end
  
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def show
    @order = Order.find(params[:id])
    @order_details = OrderDetail.where(order_id: params[:id])
    @order_customer = @order.customer_id
    @total = 0
    @order_details.each do |order_detail|
      total = order_detail.subtotal
    @total += total
    end
  end

  def update
    @order = Order.find(params[:id])
    @order.update(order_params)
    redirect_to admin_order_path(@order)
  end
  
  private
  
  def order_params
    params.require(:order).permit(:status)
  end
end

app/controllers/admins/unlocks_controller.rb
# frozen_string_literal: true

class Admins::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  def after_sign_in_path_for(resource)
    case resource
    when Admin
      admin_path          
    when Customer
      root_path             
    end
  end
  
  def after_sign_out_path_for(resource_or_scope)
    if resource_or_scope == :customer
      root_path # ログアウト後に遷移するpathを設定
    else
      new_admin_session_path
    end
  end
  

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :is_delete])
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/genres/create.html.erb
<h1>Admin::Genres#create</h1>
<p>Find me in app/views/admin/genres/create.html.erb</p>

app/views/admin/genres/edit.html.erb
<main>
  <h1>ジャンル編集</h1>
  <div class="genre-form">
    <%= form_with model: @genre, url:admin_genre_path, local:true do |f| %>
    <p>ジャンル名</p>
    <%= f.text_field :name %>
    <%= f.submit "変更を保存", class: 'button' %>
    <% end %>
  </div>
</main>

app/views/admin/genres/index.html.erb
<main>
  <% if @genre.errors.any? %>
    <h3><%= @genre.errors.count %>件のエラーが発生しました</h3>
    <% @genre.errors.full_messages.each do |message| %>
      <p class="validate"><%= message %></p>
    <% end %>
  <% end %>
  <h1>ジャンル一覧・追加</h1>
  <div class="genre-form">
    <%= form_with model: @genre, url:admin_genres_path, local:true do |f| %>
    <p>ジャンル名</p>
    <%= f.text_field :name, placeholder: "ジャンル名" %>
    <%= f.submit "新規登録", class: 'button' %>
    <% end %>
  </div>
  <div class="genre-list">
    <h3>ジャンル</h3>
    <% @genres.each do |genre| %>
    <ul>
      <li>
        <p><%= genre.name %></p>
        <%= link_to "編集する", edit_admin_genre_path(genre) %>
      </li>
    </ul>
    <% end %>
  </div>
</main>

app/views/admin/genres/update.html.erb
<h1>Admin::Genres#update</h1>
<p>Find me in app/views/admin/genres/update.html.erb</p>

app/views/admin/items/edit.html.erb
<main>
  <h1>商品編集</h1>
    <div class="form">
    <%= form_with model: @item, url:admin_item_path(@item), local:true do |f| %>
    
    <div class="form_group">
      <%= f.label :image, "商品画像", class: 'label' %>
      <%= f.attachment_field :image %>
    </div>
    <div class="form_group">
      <%= f.label :name, "商品名", class: 'label' %>
      <%= f.text_field :name, class: 'form-box' %>
    </div>
    <div class="form_group">
      <%= f.label :introduction, "商品説明", class: 'label' %>
      <%= f.text_area :introduction, class: 'form-box introduction' %>
    </div>
    <div class="form_group">
      <%= f.label :genre_id, "ジャンル", class: 'label' %>
      <%= f.collection_select :genre_id, Genre.all, :id, :name, { include_blank: '選択してください'}, class: 'form-box' %>
    </div>
    <div class="form_group">
      <%= f.label :price, "税抜価格", class: 'label' %>
      <%= f.text_field :price, class: 'form-box' %>円
    </div>
    <div class="form_group">
      <p>販売ステータス</p>
      <%= f.radio_button :is_active, Item.is_actives.key(true)  %>
      <%= f.label :is_active, Item.is_actives_i18n[:onsale]%>
      <%= f.radio_button :is_active, Item.is_actives.key(false)  %>
      <%= f.label :is_active, Item.is_actives_i18n[:offsale]  %>
    </div>
    <div class="submit-button">
      <%= f.submit "変更を保存", class: 'button' %>
    </div>
    <% end %>
  </div>
</main>

app/views/admin/items/index.html.erb
<main>
  <h1>商品一覧</h1>
  <div class="new-item-action">
    <%= link_to new_admin_item_path, class: 'new-item-button' do %>
    <i class="fas fa-plus"></i>
    <% end %>
  </div>
  <div class="item-list">
    <div class="item-list_name">
      <ul>
        <li>商品ID</li>
        <li>商品名</li>
        <li>税抜価格</li>
        <li>ジャンル</li>
        <li>ステータス</li>
      </ul>
    </div>
    <div class="item-list_content">
    <% @items.each do |item| %>
      <ul>
        <li><%= item.id %></li>
        <li><%= link_to item.name, admin_item_path(item), class: 'link' %></li>
        <li><%= item.price.to_s(:delimited) %></li>
        <li><%= item.genre.name %></li>
        <li><%= item.is_active_i18n %></li>
      </ul>
    <% end %>
    </div>
  </div>
  <%= paginate @items %>
</main>

app/views/admin/items/new.html.erb
<main>
  <% if @item.errors.any? %>
    <h3><%= @item.errors.count %>件のエラーが発生しました</h3>
    <% @item.errors.full_messages.each do |message| %>
      <p class="validate"><%= message %></p>
    <% end %>
  <% end %>
  <h1>商品新規登録</h1>
  <div class="form">
    <%= form_with model: @item, url:admin_items_path, local:true do |f| %>
    
    <div class="form_group">
      <%= f.label :image, "商品画像", class: 'label' %>
      <%= f.attachment_field :image %>
    </div>
    <div class="form_group">
      <%= f.label :name, "商品名", class: 'label' %>
      <%= f.text_field :name, placeholder: "商品名", class: 'form-box' %>
    </div>
    <div class="form_group">
      <%= f.label :introduction, "商品説明", class: 'label' %>
      <%= f.text_area :introduction, placeholder: "ここに説明文を記述します。", class: 'form-box introduction' %>
    </div>
    <div class="form_group">
      <%= f.label :genre_id, "ジャンル", class: 'label' %>
      <%= f.collection_select :genre_id, Genre.all, :id, :name, { include_blank: '選択してください'}, class: 'form-box' %>
    </div>
    <div class="form_group">
      <%= f.label :price, "税抜価格", class: 'label' %>
      <%= f.text_field :price, placeholder: "1000", class: 'form-box' %>円
    </div>
    <div class="form_group">
      <p>販売ステータス</p>
      <%= f.radio_button :is_active, Item.is_actives.key(true), checked: "checked" %>
      <%= f.label :is_active, Item.is_actives_i18n[:onsale] %>
      <%= f.radio_button :is_active, Item.is_actives.key(false)  %>
      <%= f.label :is_active, Item.is_actives_i18n[:offsale]  %>
    </div>
    <div class="submit-button">
      <%= f.submit "新規登録", class: 'button' %>
    </div>
    <% end %>
  </div>
</main>

app/views/admin/items/show.html.erb
<main>
  <h1>商品詳細</h1>
  <div class="item-content">
    <div class="item-content_image">
      <%= attachment_image_tag @item, :image, class: 'img' %>
    </div>
    <ul>
      <li>
        <p>商品名</p>
        <p><%= @item.name %></p>
      </li>
      <li>
        <p>商名説明</p>
        <p><%= @item.introduction %></p>
      </li>
      <li>
        <p>ジャンル</p>
        <p><%= @item.genre.name %></p>
      </li>
      <li>
        <p>税込価格<br>（税抜価格）</p>
        <p><%= @item.tax_price.to_s(:delimited) %>（<%= @item.price.to_s(:delimited) %>）円</p>
      </li>
      <li>
        <p>販売ステータス</p>
        <p><%= @item.is_active_i18n %></p>
      </li>
    </ul>
  </div>
  <div class="item-edit">
    <%= link_to "編集する", edit_admin_item_path(@item), class: 'edit-button' %>
  </div>
</main>

app/views/admin/orders/show.html.erb
<main>
  <h1>注文履歴詳細</h1>
  <div class="order-history">
    <dl>
      <dt>購入者</dt>
      <dd><%= link_to @order.reload_customer.full_name, admin_customer_path(@order_customer) %></dd>
    </dl>
    <dl>
      <dt>注文日</dt>
      <dd><%= @order.created_at.strftime("%Y/%m/%d") %></dd>
    </dl>
    <dl>
      <dt>配送先</dt>
      <dd>〒<%= @order.postal_code %><%= @order.address %><br><%= @order.name %></dd>
    </dl>
    <dl>
      <dt>支払方法</dt>
      <dd><%= @order.payment_i18n %></dd>
    </dl>
    <dl>
      <dt>注文ステータス</dt>
      <dd>
        <%= form_with model: @order, url:admin_order_path, local:true do |f| %>
        <%= f.select :status, Order.statuses_i18n.invert %>
        <%= f.submit "更新", class: 'button' %>
        <% end %>
      </dd>
    </dl>
  </div>
  <div class="order-product">
    <div class="order-product_content">
      <ul>
        <li>商品名</li>
        <li>単価（税込）</li>
        <li>数量</li>
        <li>小計</li>
        <li>製作ステータス</li>
      </ul>
      <% @order_details.each do |order_detail| %>
      <ul>
        <li><%= order_detail.item.name %></li>
        <li><%= order_detail.price.to_s(:delimited) %></li>
        <li><%= order_detail.amount %></li>
        <li><%= order_detail.subtotal.to_s(:delimited) %></li>
        <li>
          <%= form_with model: order_detail, url:admin_order_detail_path, local:true do |f| %>
          <%= f.select :making_status, OrderDetail.making_statuses_i18n.invert %>
          <%= f.submit "更新", class: 'button' %>
          <% end %>
        </li>
      </ul>
      <% end %>
    </div>
    <div class="order-product_price">
      <dl>
        <dt>商品合計</dt>
        <dd><%= @total.to_s(:delimited) %>円</dd>
      </dl>
      <dl>
        <dt>送料</dt>
        <dd><%= @order.postage %>円</dd>
      </dl>
      <dl>
        <dt>請求金額合計</dt>
        <dd><%= @order.price.to_s(:delimited) %>円</dd>
      </dl>
    </div>
  </div>
</main>

app/views/admin/orders/update.html.erb
<h1>Admin::Orders#update</h1>
<p>Find me in app/views/admin/orders/update.html.erb</p>